#!/usr/bin/env bash
PROJECT_NAME=cockpit-ups-wol; INSTALL_LOG=/var/log/cockpit-ups-wol/install.log; LIBEXEC_DIR=/usr/libexec/cockpit-ups-wol
ETC_DIR=/etc/cockpit-ups-wol; STATE_DIR=/var/lib/cockpit-ups-wol; BACKUP_BASE=/var/backups/cockpit-ups-wol; SYSTEMD_DIR=/etc/systemd/system
CURRENT_BACKUP=""; INSTALL_COMMITTED=0
log(){ local m="[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] $*"; printf '%s\n' "$m"; [[ -n "${INSTALL_LOG_ACTIVE:-}" ]]&&printf '%s\n' "$m">>"$INSTALL_LOG"||true; }
warn(){ log "WARN: $*"; }; die(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }; require_root(){ [[ ${EUID:-$(id -u)} -eq 0 ]]||die "installer must run as root"; }
log_init(){ install -d -m 0755 "$(dirname "$INSTALL_LOG")"; touch "$INSTALL_LOG"; chmod 0640 "$INSTALL_LOG"; INSTALL_LOG_ACTIVE=1; log "installer started"; }
platform_detect(){ [[ -r /etc/os-release ]]||die "/etc/os-release not found"; source /etc/os-release; local id="${ID:-}" like="${ID_LIKE:-}"; case " $id $like " in *" debian "*|*" ubuntu "*) DISTRO_FAMILY=debian;; *" arch "*) DISTRO_FAMILY=arch;; *" fedora "*|*" rhel "*|*" centos "*) DISTRO_FAMILY=fedora;; *) die "unsupported distribution: ${ID:-unknown}";; esac; case "$(uname -m)" in x86_64|amd64) TARGET_ARCH=amd64;; aarch64|arm64) TARGET_ARCH=arm64;; riscv64) TARGET_ARCH=riscv64;; *) die "unsupported architecture: $(uname -m)";; esac; }
installer_self_check(){ local f; for f in "$SELF_DIR/config/config.yaml.example" "$SELF_DIR/packaging/systemd/cockpit-ups-wol-agent.service" "$SELF_DIR/packaging/systemd/cockpit-ups-wol-health.service" "$SELF_DIR/packaging/systemd/cockpit-ups-wol-health.timer" "$SELF_DIR/scripts/install/nut.sh" "$SELF_DIR/scripts/install/validate.sh"; do [[ -f "$f" ]]||die "required installer source missing: $f"; done; printf 'installer-check: ok distro=%s arch=%s profile=%s\n' "$DISTRO_FAMILY" "$TARGET_ARCH" "$PROFILE"; }
confirm_install(){ ((SILENT))&&return 0; local text="Install cockpit-ups-wol in ${PROFILE} mode on ${DISTRO_FAMILY}/${TARGET_ARCH}? New installs start in dry-run mode."; if [[ "$MODE" == tui ]]&&command -v dialog>/dev/null; then dialog --yesno "$text" 10 70||exit 1; return; fi; read -r -p "$text [y/N] " r; [[ "$r" =~ ^[Yy]$ ]]||exit 1; }
backup_path_if_exists(){ local p="$1" r="${1#/}"; [[ -e "$p"||-L "$p" ]]||return 0; install -d -m 0700 "$CURRENT_BACKUP/$(dirname "$r")"; cp -a "$p" "$CURRENT_BACKUP/$r"; }
backup_begin(){ CURRENT_BACKUP="$BACKUP_BASE/$(date -u +'%Y%m%dT%H%M%SZ')-$$"; install -d -m 0700 "$CURRENT_BACKUP"; local p; for p in "$LIBEXEC_DIR" "$ETC_DIR" "$SYSTEMD_DIR/cockpit-ups-wol-agent.service" "$SYSTEMD_DIR/cockpit-ups-wol-health.service" "$SYSTEMD_DIR/cockpit-ups-wol-health.timer" /etc/nut/nut.conf /etc/nut/ups.conf /etc/nut/upsd.conf /etc/nut/upsd.users /etc/nut/upsmon.conf; do backup_path_if_exists "$p"; done; log "rollback snapshot: $CURRENT_BACKUP"; }
restore_one(){ local p="$1" s="$CURRENT_BACKUP/${1#/}"; [[ -e "$s"||-L "$s" ]]||return 0; rm -rf "$p"; install -d -m 0755 "$(dirname "$p")"; cp -a "$s" "$p"; }
rollback_install(){ [[ -n "$CURRENT_BACKUP"&&-d "$CURRENT_BACKUP" ]]||return 0; warn "rolling back project-managed changes"; local p; for p in "$LIBEXEC_DIR" "$ETC_DIR" "$SYSTEMD_DIR/cockpit-ups-wol-agent.service" "$SYSTEMD_DIR/cockpit-ups-wol-health.service" "$SYSTEMD_DIR/cockpit-ups-wol-health.timer" /etc/nut/nut.conf /etc/nut/ups.conf /etc/nut/upsd.conf /etc/nut/upsd.users /etc/nut/upsmon.conf; do restore_one "$p"; done; systemctl daemon-reload>/dev/null 2>&1||true; }
install_failure(){ local l="$1" rc="$2"; trap - ERR; warn "installer failed at line $l (rc=$rc)"; ((INSTALL_COMMITTED))||rollback_install; exit "$rc"; }
backup_commit(){ INSTALL_COMMITTED=1; log "installation committed; rollback snapshot retained at $CURRENT_BACKUP"; }
install_project_dirs(){ install -d -m 0755 "$LIBEXEC_DIR"; install -d -m 0750 "$ETC_DIR"; install -d -m 0700 "$ETC_DIR/secrets" "$STATE_DIR" "$STATE_DIR/config-history/revisions"; }
find_prebuilt(){ local n="$1" c; for c in "$BINARY_DIR/$n" "$BINARY_DIR/linux-$TARGET_ARCH/$n" "$SELF_DIR/dist/linux-$TARGET_ARCH/$n" "$SELF_DIR/dist/$TARGET_ARCH/$n"; do [[ -x "$c" ]]&&{ printf '%s\n' "$c"; return 0; }; done; return 1; }
build_from_source(){ command -v go>/dev/null||return 1; log "using development source-build fallback"; (cd "$SELF_DIR/agent"&&CGO_ENABLED=0 GOOS=linux GOARCH="$TARGET_ARCH" go build -o "$LIBEXEC_DIR/cockpit-ups-wol-agent" ./cmd/cockpit-ups-wol-agent); (cd "$SELF_DIR/agent"&&CGO_ENABLED=0 GOOS=linux GOARCH="$TARGET_ARCH" go build -o "$LIBEXEC_DIR/cockpit-ups-wolctl" ./cmd/cockpit-ups-wolctl); }
install_project_binaries(){ local a c; if a="$(find_prebuilt cockpit-ups-wol-agent)"&&c="$(find_prebuilt cockpit-ups-wolctl)"; then install -m0755 "$a" "$LIBEXEC_DIR/cockpit-ups-wol-agent"; install -m0755 "$c" "$LIBEXEC_DIR/cockpit-ups-wolctl"; else build_from_source||die "no prebuilt binaries and Go fallback unavailable"; fi; ln -sfn "$LIBEXEC_DIR/cockpit-ups-wolctl" /usr/local/sbin/cockpit-ups-wolctl; }
install_project_config(){ if [[ ! -f "$ETC_DIR/config.yaml" ]]; then install -m0600 "$SELF_DIR/config/config.yaml.example" "$ETC_DIR/config.yaml"; ((SYNOLOGY))&&sed -i '/synology_compatibility:/,/hosts_sync_seconds:/ s/enabled: false/enabled: true/' "$ETC_DIR/config.yaml"; else log "existing project config preserved"; fi; }
install_systemd_units(){ install -m0644 "$SELF_DIR/packaging/systemd/cockpit-ups-wol-agent.service" "$SYSTEMD_DIR/"; install -m0644 "$SELF_DIR/packaging/systemd/cockpit-ups-wol-health.service" "$SYSTEMD_DIR/"; install -m0644 "$SELF_DIR/packaging/systemd/cockpit-ups-wol-health.timer" "$SYSTEMD_DIR/"; }
unit_exists(){ systemctl list-unit-files "$1" --no-legend 2>/dev/null|grep -q "^$1"; }; enable_if_exists(){ unit_exists "$1"&&systemctl enable --now "$1"; }
systemd_reload_enable(){ systemctl daemon-reload; enable_if_exists cockpit.socket||warn "cockpit.socket not found"; systemctl enable --now cockpit-ups-wol-agent.service; systemctl enable --now cockpit-ups-wol-health.timer; case "$PROFILE" in local-server) enable_if_exists nut-driver-enumerator.service||true; enable_if_exists nut-server.service||true; enable_if_exists nut-monitor.service||true;; remote-client) enable_if_exists nut-monitor.service||true;; esac; }
final_report(){ printf '\nInstallation completed in dry-run mode.\n  profile: %s\n  config: %s/config.yaml\n  log: %s\n  rollback: %s\n\nBefore arming verify UPS-backed SBC power, automatic boot, network power, and UPS output-cycle behavior.\n' "$PROFILE" "$ETC_DIR" "$INSTALL_LOG" "$CURRENT_BACKUP"; }
